spring:
  application:
    name: dynamicDataScource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    druid:
      #配置初始化大小，最小，最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 6000                                # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 6000       # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 30000         # 配置一个连接在池中最小生存的时间，单位是毫秒
      pool-prepared-statements: false
      validation-query: SELECT 1


